### ISSUE TITLE
Update vtuber-group in slash command

### ISSUE THREAD

**Issue by futag** [JustHumanz/Go-Simp#269]
![image](https://user-images.githubusercontent.com/21020026/156880197-de91a1e2-c241-48ca-ad55-85085fe30751.png)
Some group not added

**Comment by JustHumanz** [comment]
that because limit from [discord](https://discord.com/developers/docs/interactions/application-commands)

![Screenshot 2022-03-06 at 13-07-13 Discord Developer Portal — API Docs for Bots and Developers](https://user-images.githubusercontent.com/43176061/156911478-f7060a63-ae5f-4de7-ac23-90231bfff5ec.png)
